name: Upload Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload Release APK
      uses: softprops/action-gh-release@v2
      with:
        files: app/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
